# Generated by Django 5.2.7 on 2025-11-28 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='Apelido')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefone')),
                ('client_debts', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Dívidas do Cliente')),
                ('initial_debt', models.DecimalField(decimal_places=2, default=0.0, help_text='Dívida cadastrada manualmente ao criar o cliente (não vem de pagamentos fiados)', max_digits=10, verbose_name='Dívida Inicial')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='client_photos/', verbose_name='Foto do Cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Quitado')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Quitação')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_payments', to='clients.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Quitação de Dívida',
                'verbose_name_plural': 'Quitações de Dívidas',
                'ordering': ['-created_at'],
            },
        ),
    ]
